export { default as CardComponent } from "./Card";
export { default as UserHeaderComponent } from "./UserHeader";
export { default as MenuComponent } from "./Menu";
export { default as WithdrawComponent } from "./Withdraw";
export { default as DepositComponent } from "./Deposit";
export { default as PromotionComponent } from "./Promotion";
export { default as ActivityComponent } from "./Activity";
export { default as ResetPasswordComponent } from "./ResetPassword";
export { default as RecordComponent } from "./Record";
export { default as PlayGameComponent } from "./PlayGame";
export { default as AccountComponent } from "./Account";
export { default as SliderbannerComponent} from "./Sliderbanner";
